### ISSUE TITLE
[Feature Request] Additional options for color customization in the Armory

### ISSUE THREAD

**Issue by leinstay** [Merathilis/ElvUI_MerathilisUI#58]
![Screenshot_1](https://user-images.githubusercontent.com/8215580/201182102-bd195f05-bf05-4bb2-b857-ff4354b365ce.png)

**Is your feature request related to a problem? Please describe.**
I apologize in advance if I missed it, but right now we have two possibilities:

1. To change the color of character item level ONLY if the "Show full item levels" option is enabled.
2. To change the background color behind character item level ONLY along with the color of the attribute titles.  

**Describe the solution you'd like**
I would like to separately adjust the color of the character item level font and background.

**Comment by Merathilis** [comment]
That is only, because you can color the "Avarage" Color if you display both. if you only display this the string is controlled by blizzard.

My advice is, to just use "OUTLINE" as font style than it is readable:

![image](https://user-images.githubusercontent.com/272403/201308586-61d70fb1-6799-4bc7-810d-2b0da6a6b853.png)
